FROM quay.io/fedora/fedora-toolbox:39

LABEL com.github.containers.toolbox="true" \
      usage="This image is meant to be used with the toolbox or distrobox command" \
      summary="A cloud-native terminal experience powered by Fedora" 

COPY ./toolboxes/fedora-toolbox/packages.fedora /toolbox-packages

RUN dnf -y upgrade && \
    dnf -y install $(<toolbox-packages) && \
    dnf clean all

RUN rm /toolbox-packages
