FROM docker.io/library/ubuntu:24.04@sha256:6015f66923d7afbc53558d7ccffd325d43b4e249f41a6e93eef074c9505d2233
# FROM https://hub.docker.com/_/ubuntu

LABEL com.github.containers.toolbox="true" \
    name="ubuntu-toolbox" \
    usage="This image is meant to be used with the toolbox or distrobox command" \
    summary="A cloud-native terminal experience powered by Ubuntu" \
    maintainer="jorge.castro@gmail.com"

COPY ./toolboxes/ubuntu-toolbox/packages.ubuntu /toolbox-packages

RUN rm /etc/apt/apt.conf.d/docker-gzip-indexes /etc/apt/apt.conf.d/docker-no-languages && \
    sed -Ei 's/^(hosts:.*)(\<files\>)\s*(.*)/\1\2 myhostname \3/' /etc/nsswitch.conf && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
    ubuntu-minimal ubuntu-standard \
    libnss-myhostname \
    flatpak-xdg-utils \
    $(cat toolbox-packages | xargs) && \
    rm -rd /var/lib/apt/lists/* && \
    rm /toolbox-packages && \
    mkdir /usr/share/empty && \
    userdel --remove ubuntu && \
    curl -sLo /usr/bin/host-spawn https://github.com/1player/host-spawn/releases/download/1.5.0/host-spawn-x86_64 && \
    chmod +x /usr/bin/host-spawn && \
    rm /etc/apt/apt.conf.d/20apt-esm-hook.conf && \
    ln -s /usr/libexec/flatpak-xdg-utils/flatpak-spawn /usr/bin/ && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/docker && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/flatpak && \ 
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/podman && \
    ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree && \
    echo "ALL ALL = (ALL) NOPASSWD: ALL" >> /etc/sudoers
