FROM ghcr.io/ublue-os/ubuntu-toolbox@sha256:293fa772b923c698ba0a68833d503a6c9a7fae3287d339f3b0ae4f995f014a8f

RUN <<EOF
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates curl socat systemd
mkdir -p /etc/apt/keyrings/
curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
sh /tmp/get-docker.sh
apt-get clean
mkdir -p /var/lib/docker
rm -rf /var/lib/docker/**
rm -f /usr/local/bin/docker
cat > /usr/lib/systemd/system/docker-setup.service <<- EEOF
[Unit]
Description=Setup Docker Socket in /var/run/
After=docker.socket
[Service]
PassEnvironment=DOCKERGROUP
ExecStart=/usr/bin/bash -c "while true; do sleep 1; /usr/bin/socat UNIX-LISTEN:/run/host/var/run/docker.sock,reuseaddr,fork,group=\${DOCKERGROUP:-docker},umask=007 UNIX-CONNECT:/var/run/docker.sock; done"
[Install]
WantedBy=sockets.target
EEOF
groupmod -g 252 docker
systemctl enable docker-setup.service
rm -rf /tmp /var/tmp
EOF
CMD ["/sbin/init"]
