FROM docker.io/library/debian:trixie@sha256:01a723bf5bfb21b9dda0c9a33e0538106e4d02cce8f557e118dd61259553d598
# FROM https://hub.docker.com/_/debian

LABEL com.github.containers.toolbox="true" \
  name="debian-toolbox" \
  usage="This image is meant to be used with the toolbox or distrobox command" \
  summary="A cloud-native terminal experience powered by Debian" \
  maintainer="justin@linux.com"

COPY ./toolboxes/debian-toolbox/packages.debian /toolbox-packages

RUN rm /etc/apt/apt.conf.d/docker-gzip-indexes /etc/apt/apt.conf.d/docker-no-languages && \
  sed -Ei 's/^(hosts:.*)(\<files\>)\s*(.*)/\1\2 myhostname \3/' /etc/nsswitch.conf && \
  apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get -y install \
  libnss-myhostname \
  flatpak-xdg-utils \
  $(cat toolbox-packages | xargs) && \
  rm -rd /var/lib/apt/lists/* && \
  rm /toolbox-packages && \
  mkdir /usr/share/empty && \
  curl -sLo /usr/bin/host-spawn https://github.com/1player/host-spawn/releases/download/1.5.0/host-spawn-x86_64 && \
  chmod +x /usr/bin/host-spawn && \
  ln -s /usr/libexec/flatpak-xdg-utils/flatpak-spawn /usr/bin/ && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/docker && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/flatpak && \ 
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/podman && \
  ln -fs /usr/bin/distrobox-host-exec /usr/local/bin/rpm-ostree && \
  echo "ALL ALL = (ALL) NOPASSWD: ALL" >> /etc/sudoers
